default: &default
  encoding: unicode
  pool: <%= ENV['DATABASE_POOL'].presence || 5 %>

development:
  <<: *default
  database: complect_development

test:
  <<: *default
  database: complect_test

production:
  <<: *default
  database: complect_production
