# *    *    *    *    *  command to be executed
# ┬    ┬    ┬    ┬    ┬
# │    │    │    │    │
# │    │    │    │    │
# │    │    │    │    └───── day of week (0 - 6) (0 or 6 are Sunday to Saturday, or use names)
# │    │    │    └────────── month (1 - 12)
# │    │    └─────────────── day of month (1 - 31)
# │    └──────────────────── hour (0 - 23)
# └───────────────────────── min (0 - 59)

schedule_charges:
  cron: "0 * * * *"
  class: "ScheduleChargesJob"

process_scheduled_charges:
  cron: "30 * * * *"
  class: "ProcessScheduledChargesJob"

process_transactions:
  cron: "*/5 * * * *"
  class: "ProcessTransactionsJob"

end_projects:
  cron: "0,30 * * * *"
  class: "EndProjectsJob"

expire_projects:
  cron: "*/5 * * * *"
  class: "ExpireProjectsJob"

transfer_foreign_currency:
  cron: "0 0 * * *"
  class: "TransferForeignCurrencyJob"

starts_in_48:
  cron: "*/5 * * * *"
  class: "StartsIn48Job"

ends_in_24:
  cron: "*/5 * * * *"
  class: "EndsIn24Job"

user_inactive:
  cron: "*/5 * * * *"
  class: "UserInactiveJob"