schedule_charges:
  cron: "0 * * * *"
  class: "ScheduleChargesJob"

process_scheduled_charges:
  cron: "30 * * * *"
  class: "ProcessScheduledChargesJob"

process_transactions:
  cron: "*/5 * * * *"
  class: "ProcessTransactionsJob"

end_projects:
  cron: "0,30 * * * *"
  class: "EndProjectsJob"

expire_projects:
  cron: "*/5 * * * *"
  class: "ExpireProjectsJob"

transfer_foreign_currency:
  cron: "0 0 * * *"
  class: "TransferForeignCurrencyJob"
